[package]
name = "high-frequency-snake"
version = "0.1.0"
edition = "2024"

[dependencies]
core_affinity = "0.8.3"
crossbeam-utils = "0.8.21"
rand = "0.9.2"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "spsc_bench"
harness = false
